### ISSUE TITLE
AlertCondition fails to reconcile after the controller pod restarts

### ISSUE THREAD

**Issue by jacob-hudson** [crossplane-contrib/crossplane-provider-newrelic#22]
### What happened?
AlertCondition resources fail to reconcile after the controller pod restarts

### How can we reproduce it?

- Install v0.2.0 of the provider
- Apply the example AlertCondition (I applied the corresponding Alert Policy too) - https://github.com/crossplane-contrib/crossplane-provider-newrelic/blob/main/examples/nrql/alertcondition.yaml
- Verify that all statuses are healthy
- Restart controller pod
- The Synced condition will record `Failed` with a reason of `ReconcileError` and the message of `observe failed: cannot run refresh: refresh failed: strconv.ParseInt: parsing "static": invalid syntax:`.  AlertConditions are completely fine before this point.  Alert Policies are unaffected.  There are no logs in the controller pod in its default configuration.  If the alert condition is of type Baseline, the error will read Baseline instead of Static

### What environment did it happen in?
Crossplane version:   1.15.2
Kubernetes Version: AWS EKS 1.27

**Comment by jacob-hudson** [comment]
When you are rebuilding the state, you have <policyID>, <conditionId>, <conditionType>

instead of "id":"1327951:6879335:static"

it should be "id":"1327951:6879335"

On new alert creation, there is no issue

**Comment by jacob-hudson** [comment]
This works as expected

```terraform import newrelic_nrql_alert_condition.complete-example 1327951:6879335:static```

Meaning the State files are being corrupted somehow as the resource are being imported correctly

**Comment by jacob-hudson** [comment]
@smcavallo Could you please take a look at this issue/PR when you get a chance?  This is preventing us from replacing the original NewRelic Provider you wrote as we have codified Alert Conditions that need to be managed

If I am completely off on teh PR< let me know - this was found when investigating/testing the provider preparing it to go to production

**Comment by smcavallo** [comment]
@jacob-hudson thank you so much for this - I will take a look and review

**Comment by smcavallo** [comment]
@jacob-hudson your fix has been merged and published to the upbound marketplace.  Thanks again for the fix (and using this provider!!!)  
https://marketplace.upbound.io/providers/crossplane-contrib/crossplane-provider-newrelic/v0.2.1
